/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2018-06-25T17:54:23-04:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 19

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 19

#define VERSION_STRING "14aefca7a435"

#endif /* __XIA_VERSION_H__ */

