/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2018-05-18T19:59:54-07:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 17

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 17

#define VERSION_STRING "839556f8f946"

#endif /* __XIA_VERSION_H__ */

