/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2017-05-04T09:41:00-04:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 14

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 14

#define VERSION_STRING "cdd0f02d0c24"

#endif /* __XIA_VERSION_H__ */

