/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2018-11-13T13:59:37-08:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 20

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 20

#define VERSION_STRING "668097e7561d"

#endif /* __XIA_VERSION_H__ */

