/* xia_version.h -- AUTOGENERATED
 *
 * Generated by gen_version.rb on 2020-07-13T15:13:47-07:00
 */

#ifndef XIA_VERSION_H
#define XIA_VERSION_H

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 21

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 21

#define VERSION_STRING "801d116fc0dc"

#endif /* __XIA_VERSION_H__ */

