TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#==================================================
# build a support library


# Test applications
PROD_IOC_Linux    += hd-adc-trace
PROD_IOC_WIN32    += hd-adc-trace
hd-adc-trace_SRCS += hd-adc-trace.c

PROD_LIBS += handel sinc

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

