
doxygen:
	doxygen

install:
	cp -f *.html /home/epics/web_software/epics
	cp -f *.png /home/epics/web_software/epics
	cp -f *.jpg /home/epics/web_software/epics
	cp -f *.pdf /home/epics/web_software/epics
	cp -rfp dxpSITORODoxygenHTML  /home/epics/web_software/epics/

clean:
	rm -rf dxpSITORODoxygenHTML/*


realclean: clean
